const { danger, fail, warn, message } = require("danger");

const pr = danger.github.pr;
const modifiedFiles = danger.git.modified_files;
const createdFiles = danger.git.created_files;
const deletedFiles = danger.git.deleted_files;
const changedFiles = [...modifiedFiles, ...createdFiles, ...deletedFiles];
const body = pr.body || "";
const title = pr.title || "";

const hasMeaningfulBody = body
  .replace(/<!--[\s\S]*?-->/g, "")
  .replace(/#+\s*(summary|description|changes|testing|verification)\s*/gi, "")
  .trim()
  .length >= 40;

if (!hasMeaningfulBody) {
  fail("PR description must explain what changed and how it was verified.");
}

const aiAttributionPattern =
  /\b(generated by|co-authored-by:\s*(chatgpt|codex|claude|cursor|copilot|qodo)|created by (chatgpt|codex|claude)|ai-generated|🤖)\b/i;

if (aiAttributionPattern.test(`${title}\n${body}`)) {
  fail("Remove AI self-attribution from the PR title/body; describe the engineering change instead.");
}

const secretLikeFiles = changedFiles.filter((file) =>
  /(^|\/)(\.env($|\.)|.*\.pem$|.*\.key$|.*\.p12$|.*\.pfx$|id_rsa$|id_ed25519$)/i.test(file)
);

if (secretLikeFiles.length > 0) {
  fail(`Secret-like files must not be committed: ${secretLikeFiles.join(", ")}`);
}

const touchesWorkflows = changedFiles.some((file) => file.startsWith(".github/workflows/"));
const touchesWebAssets = changedFiles.some((file) => file.startsWith("web/"));
const touchesWebHashGuard = changedFiles.includes("crates/openplotva-web/src/lib.rs");
const touchesProdDeploy = changedFiles.some((file) =>
  file === ".github/workflows/deploy-production.yml" || file.startsWith("deploy/production/")
);
const touchesMigrations = changedFiles.some((file) => file.startsWith("migrations/"));
const touchesPrompts = changedFiles.some((file) => file.startsWith("prompts/"));

if (touchesWebAssets && !touchesWebHashGuard) {
  fail("Changes under web/ must update the matching sha256 constants in crates/openplotva-web/src/lib.rs.");
}

if (touchesWorkflows) {
  warn("Workflow changes should be verified with actionlint and a YAML parser before merge.");
}

if (touchesProdDeploy) {
  warn("Production deploy workflow/assets changed; include an explicit deployment-risk note and verification plan.");
}

if (touchesMigrations) {
  warn("Migration changes should include up/down compatibility notes and a representative SQLx/storage check.");
}

if (touchesPrompts) {
  warn("Prompt files are cache-sensitive contracts; confirm prompt shape and role markers were preserved intentionally.");
}

const diffStats = pr.additions + pr.deletions;
if (diffStats > 1000) {
  warn(`Large PR (${diffStats} changed lines). Consider splitting unless this is generated/mechanical.`);
}

message(`Danger checked ${changedFiles.length} changed file(s).`);
