//! Rich-message composition and sending for OpenPlotva.
//!
//! [`RichMessenger`] is the single send facade for Telegram Rich Messages: it sanitizes
//! HTML at the boundary and delegates to the raw rich Bot API client, the streaming-draft
//! path (private chats), and the media uploader. The free `compose_*` functions build the
//! approved rich layouts (currency table, song, gallery, draw progress, leaderboard) as
//! sanitized rich HTML; they are pure and unit-tested so the visual contract is pinned
//! independently of the send path.

use openplotva_media::uploader::UploaderClient;
use openplotva_telegram::{
    RichApiClient, RichApiError, RichMessage, RichSendOptions, escape_telegram_html_text,
    sanitize_rich_html,
};
use serde_json::Value;

/// Send facade for rich messages.
#[derive(Clone, Debug)]
pub struct RichMessenger {
    rich: RichApiClient,
    uploader: UploaderClient,
}

impl RichMessenger {
    #[must_use]
    pub fn new(rich: RichApiClient, uploader: UploaderClient) -> Self {
        Self { rich, uploader }
    }

    /// Access the media uploader (to publish generated bytes/URLs before composing media).
    #[must_use]
    pub fn uploader(&self) -> &UploaderClient {
        &self.uploader
    }

    /// Send a rich message, sanitizing the HTML at the boundary.
    pub async fn send(
        &self,
        chat_id: i64,
        html: &str,
        options: &RichSendOptions,
    ) -> Result<RichMessage, RichApiError> {
        self.rich
            .send_rich_message(chat_id, &sanitize_rich_html(html), options)
            .await
    }

    /// Replace a message's content with new rich HTML in place (group pseudo-streaming).
    pub async fn edit(
        &self,
        chat_id: i64,
        message_id: i64,
        html: &str,
        reply_markup: Option<Value>,
    ) -> Result<(), RichApiError> {
        self.rich
            .edit_message_text_rich(chat_id, message_id, &sanitize_rich_html(html), reply_markup)
            .await
    }

    /// Stream a partial rich message into an animated draft (private chats only).
    pub async fn draft(
        &self,
        chat_id: i64,
        draft_id: i64,
        html: &str,
        message_thread_id: Option<i64>,
    ) -> Result<(), RichApiError> {
        self.rich
            .send_rich_message_draft(
                chat_id,
                draft_id,
                &sanitize_rich_html(html),
                message_thread_id,
            )
            .await
    }
}

fn esc(value: &str) -> String {
    escape_telegram_html_text(value)
}

/// Escape text and turn newlines into `<br>` for use inside a rich block.
fn esc_multiline(value: &str) -> String {
    esc(value).replace('\n', "<br>")
}

/// A single currency row for [`compose_rates_table`].
#[derive(Clone, Debug)]
pub struct RateRow {
    pub label: String,
    pub value: String,
    pub delta: String,
}

/// Compose the currency-rates rich table (replaces the whitespace pseudo-grid).
#[must_use]
pub fn compose_rates_table(header: &str, rows: &[RateRow], footer: &str) -> String {
    let mut html = String::new();
    html.push_str(&format!("<h3>{}</h3>", esc(header)));
    html.push_str("<table bordered striped><tr><th>Пара</th><th>Курс</th><th>За сутки</th></tr>");
    for row in rows {
        html.push_str(&format!(
            "<tr><td>{}</td><td align=\"right\">{}</td><td align=\"right\">{}</td></tr>",
            esc(&row.label),
            esc(&row.value),
            esc(&row.delta),
        ));
    }
    html.push_str("</table>");
    if !footer.trim().is_empty() {
        html.push_str(&format!("<footer>{}</footer>", esc(footer)));
    }
    sanitize_rich_html(&html)
}

/// Inputs for [`compose_song_message`].
#[derive(Clone, Debug)]
pub struct SongMessage<'a> {
    pub title: &'a str,
    pub styles: &'a str,
    pub audio_url: &'a str,
    pub lyrics: &'a str,
    /// Pre-built rich HTML for the author/credit footer (already escaped/sanitized fragments).
    pub footer_html: &'a str,
}

/// Compose a song as a single rich message: title, styles, inline audio, collapsible
/// lyrics, then the author footer.
#[must_use]
pub fn compose_song_message(song: &SongMessage<'_>) -> String {
    let mut html = String::new();
    html.push_str(&format!("<h3>🎵 {}</h3>", esc(song.title)));
    if !song.styles.trim().is_empty() {
        html.push_str(&format!("<p><b>Стили:</b> <i>{}</i></p>", esc(song.styles)));
    }
    html.push_str(&format!("<audio src=\"{}\"></audio>", esc(song.audio_url)));
    if !song.lyrics.trim().is_empty() {
        html.push_str(&format!(
            "<details><summary>📜 Текст песни</summary><blockquote>{}</blockquote></details>",
            esc_multiline(song.lyrics),
        ));
    }
    if !song.footer_html.trim().is_empty() {
        html.push_str(&format!("<footer>{}</footer>", song.footer_html));
    }
    sanitize_rich_html(&html)
}

/// Compose a finished image result: a single `<img>` for one image, a `<tg-slideshow>`
/// for several. `caption_html` is pre-built rich HTML; `prompt_spoiler` is plain text.
#[must_use]
pub fn compose_gallery(
    image_urls: &[String],
    caption_html: &str,
    prompt_spoiler: Option<&str>,
) -> String {
    let mut html = String::new();
    match image_urls {
        [] => {}
        [single] => {
            html.push_str(&format!("<img src=\"{}\"/>", esc(single)));
            if !caption_html.trim().is_empty() {
                html.push_str(&format!("<p>{caption_html}</p>"));
            }
        }
        many => {
            html.push_str("<tg-slideshow>");
            for url in many {
                html.push_str(&format!("<img src=\"{}\"/>", esc(url)));
            }
            if !caption_html.trim().is_empty() {
                html.push_str(&format!("<figcaption>{caption_html}</figcaption>"));
            }
            html.push_str("</tg-slideshow>");
        }
    }
    if let Some(prompt) = prompt_spoiler {
        if !prompt.trim().is_empty() {
            html.push_str(&format!(
                "<p><b>Промпт:</b> <tg-spoiler>{}</tg-spoiler></p>",
                esc(prompt),
            ));
        }
    }
    sanitize_rich_html(&html)
}

/// Progressive draw state for the in-place updated draw message.
#[must_use]
pub fn compose_draw_progress(
    status: &str,
    done: usize,
    total: Option<usize>,
    image_urls: &[String],
) -> String {
    let mut html = String::new();
    let counter = match total {
        Some(total) if total > 0 => format!(" {done} из {total}"),
        _ if done > 0 => format!(" {done}"),
        _ => String::new(),
    };
    html.push_str(&format!(
        "<p>✨ <i>{}{}</i></p>",
        esc(status),
        esc(&counter)
    ));
    match image_urls {
        [] => {}
        [single] => html.push_str(&format!("<img src=\"{}\"/>", esc(single))),
        many => {
            html.push_str("<tg-slideshow>");
            for url in many {
                html.push_str(&format!("<img src=\"{}\"/>", esc(url)));
            }
            html.push_str("</tg-slideshow>");
        }
    }
    sanitize_rich_html(&html)
}

/// One leaderboard standing for [`compose_leaderboard`].
#[derive(Clone, Debug)]
pub struct LeaderboardRow {
    pub rank_title: String,
    pub name: String,
    pub wins: i64,
}

/// Compose the yearly check-in leaderboard as a rich table with medals for the top three.
#[must_use]
pub fn compose_leaderboard(theme: &str, rows: &[LeaderboardRow]) -> String {
    let mut html = String::new();
    html.push_str(&format!("<h3>🏆 {} — Лидеры года</h3>", esc(theme)));
    html.push_str(
        "<table bordered striped><tr><th>#</th><th>Титул</th><th>Имя</th><th>Побед</th></tr>",
    );
    for (index, row) in rows.iter().enumerate() {
        let place = match index {
            0 => "🥇".to_owned(),
            1 => "🥈".to_owned(),
            2 => "🥉".to_owned(),
            other => (other + 1).to_string(),
        };
        html.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td align=\"right\">{}</td></tr>",
            place,
            esc(&row.rank_title),
            esc(&row.name),
            row.wins,
        ));
    }
    html.push_str("</table>");
    sanitize_rich_html(&html)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rates_table_is_rich() {
        let rows = vec![
            RateRow {
                label: "USD/RUB".to_owned(),
                value: "78.42".to_owned(),
                delta: "+0.15".to_owned(),
            },
            RateRow {
                label: "EUR/RUB".to_owned(),
                value: "85.10".to_owned(),
                delta: "-0.20".to_owned(),
            },
        ];
        let html = compose_rates_table("Курсы", &rows, "источник: ЦБ РФ");
        assert_eq!(
            html,
            "<h3>Курсы</h3><table bordered striped><tr><th>Пара</th><th>Курс</th><th>За сутки</th></tr>\
<tr><td>USD/RUB</td><td align=\"right\">78.42</td><td align=\"right\">+0.15</td></tr>\
<tr><td>EUR/RUB</td><td align=\"right\">85.10</td><td align=\"right\">-0.20</td></tr></table>\
<footer>источник: ЦБ РФ</footer>"
        );
    }

    #[test]
    fn song_has_audio_details_and_footer_in_order() {
        let song = SongMessage {
            title: "Песня",
            styles: "synthwave, dreamy",
            audio_url: "https://plotva.geta.moe/x.mp3",
            lyrics: "строка 1\nстрока 2",
            footer_html: "за авторством <i>Автор</i>",
        };
        let html = compose_song_message(&song);
        let audio = html.find("<audio").unwrap();
        let details = html.find("<details>").unwrap();
        let footer = html.find("<footer>").unwrap();
        assert!(audio < details && details < footer);
        assert!(html.contains(r#"<audio src="https://plotva.geta.moe/x.mp3"></audio>"#));
        assert!(html.contains("<blockquote>строка 1<br/>строка 2</blockquote>"));
        assert!(html.contains("<footer>за авторством <i>Автор</i></footer>"));
    }

    #[test]
    fn gallery_one_image_is_inline_many_is_slideshow() {
        let one = compose_gallery(&["https://h/a.png".to_owned()], "cap", None);
        assert_eq!(one, r#"<img src="https://h/a.png"/><p>cap</p>"#);
        let many = compose_gallery(
            &["https://h/a.png".to_owned(), "https://h/b.png".to_owned()],
            "cap",
            Some("prompt"),
        );
        assert!(many.starts_with("<tg-slideshow>"));
        assert!(many.contains("<figcaption>cap</figcaption>"));
        assert!(many.contains("<tg-spoiler>prompt</tg-spoiler>"));
    }

    #[test]
    fn draw_progress_shows_counter_and_partial_media() {
        let html = compose_draw_progress("рисую…", 2, Some(3), &["https://h/a.png".to_owned()]);
        assert!(html.contains("<p>✨ <i>рисую… 2 из 3</i></p>"));
        assert!(html.contains(r#"<img src="https://h/a.png"/>"#));
        let queue = compose_draw_progress("ожидаю очереди", 0, None, &[]);
        assert_eq!(queue, "<p>✨ <i>ожидаю очереди</i></p>");
    }

    #[test]
    fn leaderboard_has_medals() {
        let rows = vec![
            LeaderboardRow {
                rank_title: "Король".to_owned(),
                name: "Алиса".to_owned(),
                wins: 12,
            },
            LeaderboardRow {
                rank_title: "Принц".to_owned(),
                name: "Боб".to_owned(),
                wins: 9,
            },
        ];
        let html = compose_leaderboard("Кот дня", &rows);
        assert!(html.contains("<h3>🏆 Кот дня — Лидеры года</h3>"));
        assert!(
            html.contains("<td>🥇</td><td>Король</td><td>Алиса</td><td align=\"right\">12</td>")
        );
        assert!(html.contains("<td>🥈</td>"));
    }

    #[test]
    fn escapes_dynamic_values() {
        let rows = vec![RateRow {
            label: "<b>x</b>".to_owned(),
            value: "1 & 2".to_owned(),
            delta: "<".to_owned(),
        }];
        let html = compose_rates_table("a<b", &rows, "");
        assert!(html.contains("<h3>a&lt;b</h3>"));
        assert!(html.contains("<td>&lt;b&gt;x&lt;/b&gt;</td>"));
        assert!(html.contains("<td align=\"right\">1 &amp; 2</td>"));
    }
}
