//! Rich-message composition and sending for OpenPlotva.
//!
//! [`RichMessenger`] is the single send facade for Telegram Rich Messages: it sanitizes
//! HTML at the boundary and delegates to the raw rich Bot API client, the streaming-draft
//! path (private chats), and the media uploader. The free `compose_*` functions build the
//! approved rich layouts (currency table, song, gallery, draw progress, leaderboard) as
//! sanitized rich HTML; they are pure and unit-tested so the visual contract is pinned
//! independently of the send path.

use std::future::Future;
use std::pin::Pin;

use openplotva_media::uploader::{UploaderClient, UploaderError};
use openplotva_telegram::{
    RichApiClient, RichApiError, RichMessage, RichSendOptions, escape_telegram_html_text,
    format_rich_html, sanitize_rich_html,
};
use serde_json::Value;

/// Send facade for rich messages.
#[derive(Clone, Debug)]
pub struct RichMessenger {
    rich: RichApiClient,
    uploader: UploaderClient,
}

impl RichMessenger {
    #[must_use]
    pub fn new(rich: RichApiClient, uploader: UploaderClient) -> Self {
        Self { rich, uploader }
    }

    /// Access the media uploader (to publish generated bytes/URLs before composing media).
    #[must_use]
    pub fn uploader(&self) -> &UploaderClient {
        &self.uploader
    }

    /// Send a rich message, sanitizing the HTML at the boundary.
    pub async fn send(
        &self,
        chat_id: i64,
        html: &str,
        options: &RichSendOptions,
    ) -> Result<RichMessage, RichApiError> {
        self.rich
            .send_rich_message(chat_id, &format_rich_html(html), options)
            .await
    }

    /// Replace a message's content with new rich HTML in place (group pseudo-streaming).
    pub async fn edit(
        &self,
        chat_id: i64,
        message_id: i64,
        html: &str,
        reply_markup: Option<Value>,
    ) -> Result<(), RichApiError> {
        self.rich
            .edit_message_text_rich(chat_id, message_id, &format_rich_html(html), reply_markup)
            .await
    }

    /// Stream a partial rich message into an animated draft (private chats only).
    pub async fn draft(
        &self,
        chat_id: i64,
        draft_id: i64,
        html: &str,
        message_thread_id: Option<i64>,
    ) -> Result<(), RichApiError> {
        self.rich
            .send_rich_message_draft(
                chat_id,
                draft_id,
                &format_rich_html(html),
                message_thread_id,
            )
            .await
    }
}

/// Boxed future returned by [`RichSender`] send/edit/draft methods.
pub type RichSendFuture<'a, T> = Pin<Box<dyn Future<Output = Result<T, RichApiError>> + Send + 'a>>;
/// Boxed future returned by [`RichSender`] upload methods.
pub type RichUploadFuture<'a> =
    Pin<Box<dyn Future<Output = Result<String, UploaderError>> + Send + 'a>>;

/// Abstraction over rich sending so handlers/workers can be unit-tested with a mock
/// instead of issuing real Bot API / uploader HTTP calls.
pub trait RichSender: Send + Sync + std::fmt::Debug {
    /// Send a rich message; resolves to the sent message id.
    fn send_rich<'a>(
        &'a self,
        chat_id: i64,
        html: &'a str,
        options: &'a RichSendOptions,
    ) -> RichSendFuture<'a, i64>;
    /// Replace a message's rich content in place.
    fn edit_rich<'a>(
        &'a self,
        chat_id: i64,
        message_id: i64,
        html: &'a str,
        reply_markup: Option<Value>,
    ) -> RichSendFuture<'a, ()>;
    /// Stream a partial rich draft (private chats only).
    fn draft_rich<'a>(
        &'a self,
        chat_id: i64,
        draft_id: i64,
        html: &'a str,
        message_thread_id: Option<i64>,
    ) -> RichSendFuture<'a, ()>;
    /// Publish bytes to the media host; resolves to a public HTTPS URL.
    fn upload_bytes<'a>(
        &'a self,
        bytes: Vec<u8>,
        content_type: &'a str,
        explicit_name: Option<&'a str>,
    ) -> RichUploadFuture<'a>;
    /// Hand a remote URL to the media host; resolves to a public HTTPS URL.
    fn upload_url<'a>(
        &'a self,
        source_url: &'a str,
        explicit_name: Option<&'a str>,
    ) -> RichUploadFuture<'a>;
}

impl RichSender for RichMessenger {
    fn send_rich<'a>(
        &'a self,
        chat_id: i64,
        html: &'a str,
        options: &'a RichSendOptions,
    ) -> RichSendFuture<'a, i64> {
        Box::pin(async move { Ok(self.send(chat_id, html, options).await?.id) })
    }

    fn edit_rich<'a>(
        &'a self,
        chat_id: i64,
        message_id: i64,
        html: &'a str,
        reply_markup: Option<Value>,
    ) -> RichSendFuture<'a, ()> {
        Box::pin(async move { self.edit(chat_id, message_id, html, reply_markup).await })
    }

    fn draft_rich<'a>(
        &'a self,
        chat_id: i64,
        draft_id: i64,
        html: &'a str,
        message_thread_id: Option<i64>,
    ) -> RichSendFuture<'a, ()> {
        Box::pin(async move { self.draft(chat_id, draft_id, html, message_thread_id).await })
    }

    fn upload_bytes<'a>(
        &'a self,
        bytes: Vec<u8>,
        content_type: &'a str,
        explicit_name: Option<&'a str>,
    ) -> RichUploadFuture<'a> {
        Box::pin(async move {
            self.uploader
                .upload_bytes(bytes, content_type, explicit_name)
                .await
        })
    }

    fn upload_url<'a>(
        &'a self,
        source_url: &'a str,
        explicit_name: Option<&'a str>,
    ) -> RichUploadFuture<'a> {
        Box::pin(async move { self.uploader.upload_url(source_url, explicit_name).await })
    }
}

/// A captured [`RichSender::send_rich`] call, for assertions in handler tests.
#[cfg(test)]
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct RichSendCall {
    pub chat_id: i64,
    pub html: String,
    pub reply_to_message_id: Option<i64>,
    pub allow_sending_without_reply: bool,
    pub message_thread_id: Option<i64>,
}

/// Test double capturing rich sends/edits/drafts/uploads without any HTTP. Shared
/// across scenario handler tests so they assert composed HTML + reply options.
#[cfg(test)]
#[derive(Debug, Default)]
pub(crate) struct MockRichSender {
    pub sent: std::sync::Mutex<Vec<RichSendCall>>,
    pub edited: std::sync::Mutex<Vec<(i64, i64, String)>>,
    pub drafts: std::sync::Mutex<Vec<(i64, i64, String)>>,
}

#[cfg(test)]
impl RichSender for MockRichSender {
    fn send_rich<'a>(
        &'a self,
        chat_id: i64,
        html: &'a str,
        options: &'a RichSendOptions,
    ) -> RichSendFuture<'a, i64> {
        self.sent
            .lock()
            .expect("mock rich sender sent mutex should not be poisoned")
            .push(RichSendCall {
                chat_id,
                html: html.to_owned(),
                reply_to_message_id: options.reply_to_message_id,
                allow_sending_without_reply: options.allow_sending_without_reply,
                message_thread_id: options.message_thread_id,
            });
        Box::pin(async { Ok(1001) })
    }

    fn edit_rich<'a>(
        &'a self,
        chat_id: i64,
        message_id: i64,
        html: &'a str,
        _reply_markup: Option<Value>,
    ) -> RichSendFuture<'a, ()> {
        self.edited
            .lock()
            .expect("mock rich sender edited mutex should not be poisoned")
            .push((chat_id, message_id, html.to_owned()));
        Box::pin(async { Ok(()) })
    }

    fn draft_rich<'a>(
        &'a self,
        chat_id: i64,
        draft_id: i64,
        html: &'a str,
        _message_thread_id: Option<i64>,
    ) -> RichSendFuture<'a, ()> {
        self.drafts
            .lock()
            .expect("mock rich sender drafts mutex should not be poisoned")
            .push((chat_id, draft_id, html.to_owned()));
        Box::pin(async { Ok(()) })
    }

    fn upload_bytes<'a>(
        &'a self,
        _bytes: Vec<u8>,
        _content_type: &'a str,
        _explicit_name: Option<&'a str>,
    ) -> RichUploadFuture<'a> {
        Box::pin(async { Ok("https://plotva.geta.moe/media/mock.bin".to_owned()) })
    }

    fn upload_url<'a>(
        &'a self,
        source_url: &'a str,
        _explicit_name: Option<&'a str>,
    ) -> RichUploadFuture<'a> {
        let url = source_url.to_owned();
        Box::pin(async move { Ok(url) })
    }
}

fn esc(value: &str) -> String {
    escape_telegram_html_text(value)
}

/// Escape text and turn newlines into `<br>` for use inside a rich block.
fn esc_multiline(value: &str) -> String {
    esc(value).replace('\n', "<br>")
}

/// A single currency row for [`compose_rates_table`].
#[derive(Clone, Debug)]
pub struct RateRow {
    pub label: String,
    pub value: String,
    pub delta: String,
}

/// Compose the currency-rates rich table (replaces the whitespace pseudo-grid).
#[must_use]
pub fn compose_rates_table(header: &str, rows: &[RateRow], footer: &str) -> String {
    let mut html = String::new();
    html.push_str(&format!("<h3>{}</h3>", esc(header)));
    html.push_str("<table bordered striped><tr><th>Пара</th><th>Курс</th><th>Динамика</th></tr>");
    for row in rows {
        html.push_str(&format!(
            "<tr><td>{}</td><td align=\"right\">{}</td><td align=\"right\">{}</td></tr>",
            esc(&row.label),
            esc(&row.value),
            esc(&row.delta),
        ));
    }
    html.push_str("</table>");
    if !footer.trim().is_empty() {
        html.push_str(&format!("<footer>{}</footer>", esc(footer)));
    }
    sanitize_rich_html(&html)
}

/// Inputs for [`compose_song_message`].
#[derive(Clone, Debug)]
pub struct SongMessage<'a> {
    pub title: &'a str,
    pub styles: &'a str,
    pub audio_url: &'a str,
    pub lyrics: &'a str,
    /// Pre-built rich HTML for the author/credit footer (already escaped/sanitized fragments).
    pub footer_html: &'a str,
}

/// Compose a song as a single rich message: title, styles, inline audio, collapsible
/// lyrics, then the author footer.
#[must_use]
pub fn compose_song_message(song: &SongMessage<'_>) -> String {
    let mut html = String::new();
    html.push_str(&format!("<h3>🎵 {}</h3>", esc(song.title)));
    if !song.styles.trim().is_empty() {
        html.push_str(&format!("<p><b>Стили:</b> <i>{}</i></p>", esc(song.styles)));
    }
    html.push_str(&format!("<audio src=\"{}\"></audio>", esc(song.audio_url)));
    if !song.lyrics.trim().is_empty() {
        html.push_str(&format!(
            "<details><summary>📜 Текст песни</summary><blockquote>{}</blockquote></details>",
            esc_multiline(song.lyrics),
        ));
    }
    if !song.footer_html.trim().is_empty() {
        html.push_str(&format!("<footer>{}</footer>", song.footer_html));
    }
    sanitize_rich_html(&html)
}

/// Append the gallery media body: a single `<img>` for one image, a `<tg-collage>` for
/// several, with the caption inlined (`<p>` for one, `<figcaption>` for many). Shared by the
/// final gallery and the progressive draw message so they render identically below the
/// progress line.
fn append_gallery_media(html: &mut String, image_urls: &[String], caption_html: &str) {
    match image_urls {
        [] => {}
        [single] => {
            html.push_str(&format!("<img src=\"{}\"/>", esc(single)));
            if !caption_html.trim().is_empty() {
                html.push_str(&format!("<p>{caption_html}</p>"));
            }
        }
        many => {
            html.push_str("<tg-collage>");
            for url in many {
                html.push_str(&format!("<img src=\"{}\"/>", esc(url)));
            }
            if !caption_html.trim().is_empty() {
                html.push_str(&format!("<figcaption>{caption_html}</figcaption>"));
            }
            html.push_str("</tg-collage>");
        }
    }
}

/// Compose a finished image result: a single `<img>` for one image, a `<tg-collage>`
/// for several. `caption_html` is pre-built rich HTML; `prompt_spoiler` is plain text.
#[must_use]
pub fn compose_gallery(
    image_urls: &[String],
    caption_html: &str,
    prompt_spoiler: Option<&str>,
) -> String {
    let mut html = String::new();
    append_gallery_media(&mut html, image_urls, caption_html);
    if let Some(prompt) = prompt_spoiler
        && !prompt.trim().is_empty()
    {
        html.push_str(&format!(
            "<p><b>Промпт:</b> <tg-spoiler>{}</tg-spoiler></p>",
            esc(prompt),
        ));
    }
    sanitize_rich_html(&html)
}

/// Custom emoji statuses for the draw message. The literal `⏳`/`✨` inside the tag is the
/// fallback when the custom emoji can't render. Each is sent as the sole message content so
/// Telegram renders it large (full-line).
const DRAW_WAITING_EMOJI_ID: &str = "5298571865969695917";
const DRAW_PROGRESS_EMOJI_ID: &str = "5298651821080879865";

/// Drawing start state, before any image is ready: the bare drawing emoji, sent as the sole
/// message content so Telegram renders it large (full-line).
#[must_use]
pub fn compose_draw_started() -> String {
    sanitize_rich_html(&format!(
        "<tg-emoji emoji-id=\"{DRAW_PROGRESS_EMOJI_ID}\">✨</tg-emoji>"
    ))
}

/// Progressive draw state, once images start arriving: a progress line (the drawing emoji
/// followed by "N из M") above the exact same gallery layout the final message uses, so the
/// only visible difference from the finished result is this leading progress line. The full
/// caption is shown from the first image. With no images yet this falls back to the bare
/// drawing emoji.
#[must_use]
pub fn compose_draw_progress(image_urls: &[String], total: usize, caption_html: &str) -> String {
    if image_urls.is_empty() {
        return compose_draw_started();
    }
    let mut html = format!(
        "<p><tg-emoji emoji-id=\"{DRAW_PROGRESS_EMOJI_ID}\">✨</tg-emoji> {} из {}</p>",
        image_urls.len(),
        total.max(image_urls.len()),
    );
    append_gallery_media(&mut html, image_urls, caption_html);
    sanitize_rich_html(&html)
}

/// Queue-wait state for the draw message: the bare waiting emoji.
#[must_use]
pub fn compose_draw_waiting() -> String {
    sanitize_rich_html(&format!(
        "<tg-emoji emoji-id=\"{DRAW_WAITING_EMOJI_ID}\">⏳</tg-emoji>"
    ))
}

/// A plain notice for the draw message (safety block, failure), as one rich paragraph.
#[must_use]
pub fn compose_draw_notice(text: &str) -> String {
    sanitize_rich_html(&format!("<p>{}</p>", esc_multiline(text)))
}

/// One leaderboard standing for [`compose_leaderboard`].
#[derive(Clone, Debug)]
pub struct LeaderboardRow {
    pub rank_title: String,
    pub name: String,
    pub wins: i64,
}

/// Compose the yearly check-in leaderboard as a rich table with medals for the top three.
#[must_use]
pub fn compose_leaderboard(theme: &str, rows: &[LeaderboardRow]) -> String {
    let mut html = String::new();
    html.push_str(&format!("<h3>🏆 {} — Лидеры года</h3>", esc(theme)));
    html.push_str(
        "<table bordered striped><tr><th>#</th><th>Титул</th><th>Имя</th><th>Побед</th></tr>",
    );
    for (index, row) in rows.iter().enumerate() {
        let place = match index {
            0 => "🥇".to_owned(),
            1 => "🥈".to_owned(),
            2 => "🥉".to_owned(),
            other => (other + 1).to_string(),
        };
        html.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td align=\"right\">{}</td></tr>",
            place,
            esc(&row.rank_title),
            esc(&row.name),
            row.wins,
        ));
    }
    html.push_str("</table>");
    sanitize_rich_html(&html)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn mock_rich_sender_captures_send_and_edit() {
        let mock = MockRichSender::default();
        let options = RichSendOptions {
            reply_to_message_id: Some(99),
            allow_sending_without_reply: true,
            ..RichSendOptions::default()
        };
        let id = mock
            .send_rich(7, "<b>x</b>", &options)
            .await
            .expect("mock rich send should succeed");
        assert_eq!(id, 1001);
        mock.edit_rich(7, id, "<i>y</i>", None)
            .await
            .expect("mock rich edit should succeed");
        let sent = mock
            .sent
            .lock()
            .expect("mock rich sender sent mutex should not be poisoned");
        assert_eq!(sent.len(), 1);
        assert_eq!(sent[0].chat_id, 7);
        assert_eq!(sent[0].html, "<b>x</b>");
        assert_eq!(sent[0].reply_to_message_id, Some(99));
        assert!(sent[0].allow_sending_without_reply);
        assert_eq!(
            mock.edited
                .lock()
                .expect("mock rich sender edited mutex should not be poisoned")
                .as_slice(),
            &[(7, 1001, "<i>y</i>".to_owned())]
        );
    }

    #[test]
    fn rates_table_is_rich() {
        let rows = vec![
            RateRow {
                label: "USD/RUB".to_owned(),
                value: "78.42".to_owned(),
                delta: "+0.15".to_owned(),
            },
            RateRow {
                label: "EUR/RUB".to_owned(),
                value: "85.10".to_owned(),
                delta: "-0.20".to_owned(),
            },
        ];
        let html = compose_rates_table("Курсы", &rows, "источник: ЦБ РФ");
        assert_eq!(
            html,
            "<h3>Курсы</h3><table bordered striped><tr><th>Пара</th><th>Курс</th><th>Динамика</th></tr>\
<tr><td>USD/RUB</td><td align=\"right\">78.42</td><td align=\"right\">+0.15</td></tr>\
<tr><td>EUR/RUB</td><td align=\"right\">85.10</td><td align=\"right\">-0.20</td></tr></table>\
<footer>источник: ЦБ РФ</footer>"
        );
    }

    #[test]
    fn song_has_audio_details_and_footer_in_order() {
        let song = SongMessage {
            title: "Песня",
            styles: "synthwave, dreamy",
            audio_url: "https://plotva.geta.moe/x.mp3",
            lyrics: "строка 1\nстрока 2",
            footer_html: "за авторством <i>Автор</i>",
        };
        let html = compose_song_message(&song);
        let audio = html.find("<audio").expect("song should include audio");
        let details = html.find("<details>").expect("song should include details");
        let footer = html.find("<footer>").expect("song should include footer");
        assert!(audio < details && details < footer);
        assert!(html.contains(r#"<audio src="https://plotva.geta.moe/x.mp3"></audio>"#));
        assert!(html.contains("<blockquote>строка 1<br/>строка 2</blockquote>"));
        assert!(html.contains("<footer>за авторством <i>Автор</i></footer>"));
    }

    #[test]
    fn gallery_one_image_is_inline_many_is_collage() {
        let one = compose_gallery(&["https://h/a.png".to_owned()], "cap", None);
        assert_eq!(one, r#"<img src="https://h/a.png"/><p>cap</p>"#);
        let many = compose_gallery(
            &["https://h/a.png".to_owned(), "https://h/b.png".to_owned()],
            "cap",
            Some("prompt"),
        );
        assert!(many.starts_with("<tg-collage>"));
        assert!(many.contains("<figcaption>cap</figcaption>"));
        assert!(many.contains("<tg-spoiler>prompt</tg-spoiler>"));
    }

    #[test]
    fn draw_started_is_bare_emoji() {
        assert_eq!(
            compose_draw_started(),
            "<tg-emoji emoji-id=\"5298651821080879865\">✨</tg-emoji>"
        );
    }

    #[test]
    fn draw_progress_has_count_line_then_gallery_with_caption() {
        // No images yet → falls back to the bare drawing emoji (renders large).
        assert_eq!(compose_draw_progress(&[], 2, "cap"), compose_draw_started());

        // First of two → "1 из 2" line above the image, with the full caption already shown.
        let one = compose_draw_progress(&["https://h/a.png".to_owned()], 2, "автор");
        assert!(
            one.starts_with(
                "<p><tg-emoji emoji-id=\"5298651821080879865\">✨</tg-emoji> 1 из 2</p>"
            )
        );
        assert!(one.contains(r#"<img src="https://h/a.png"/>"#));
        assert!(one.contains("автор"));

        // Several → the same collage layout as the final gallery, below the progress line.
        let many = compose_draw_progress(
            &["https://h/a.png".to_owned(), "https://h/b.png".to_owned()],
            2,
            "автор",
        );
        assert!(
            many.starts_with(
                "<p><tg-emoji emoji-id=\"5298651821080879865\">✨</tg-emoji> 2 из 2</p>"
            )
        );
        assert!(many.contains("<tg-collage>"));
        assert!(many.contains(r#"<img src="https://h/b.png"/>"#));
        assert!(many.contains("<figcaption>автор</figcaption>"));
    }

    #[test]
    fn draw_waiting_is_bare_emoji() {
        assert_eq!(
            compose_draw_waiting(),
            "<tg-emoji emoji-id=\"5298571865969695917\">⏳</tg-emoji>"
        );
    }

    #[test]
    fn draw_notice_escapes_and_breaks_lines() {
        let html = compose_draw_notice("сбой <x>\nповтор");
        assert_eq!(html, "<p>сбой &lt;x&gt;<br/>повтор</p>");
    }

    #[test]
    fn leaderboard_has_medals() {
        let rows = vec![
            LeaderboardRow {
                rank_title: "Король".to_owned(),
                name: "Алиса".to_owned(),
                wins: 12,
            },
            LeaderboardRow {
                rank_title: "Принц".to_owned(),
                name: "Боб".to_owned(),
                wins: 9,
            },
        ];
        let html = compose_leaderboard("Кот дня", &rows);
        assert!(html.contains("<h3>🏆 Кот дня — Лидеры года</h3>"));
        assert!(
            html.contains("<td>🥇</td><td>Король</td><td>Алиса</td><td align=\"right\">12</td>")
        );
        assert!(html.contains("<td>🥈</td>"));
    }

    #[test]
    fn escapes_dynamic_values() {
        let rows = vec![RateRow {
            label: "<b>x</b>".to_owned(),
            value: "1 & 2".to_owned(),
            delta: "<".to_owned(),
        }];
        let html = compose_rates_table("a<b", &rows, "");
        assert!(html.contains("<h3>a&lt;b</h3>"));
        assert!(html.contains("<td>&lt;b&gt;x&lt;/b&gt;</td>"));
        assert!(html.contains("<td align=\"right\">1 &amp; 2</td>"));
    }
}
